services:
  api:
    container_name: mymicroservice
    image: mymicroservice
    build: .
    environment:
      DatabaseServer: "sqlserver"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "VeryComplex123Password"
      DatabaseName: "mym"
    ports:
      - "3000:8080"
    networks:
      - micronet
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment: 
      - MSSQL_SA_PASSWORD=VeryComplex123Password
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1433:1433"
    networks:
      - micronet
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:

networks:
  micronet:
    driver: bridge